const query = typeof location === 'undefined' ? new URLSearchParams() : new URLSearchParams(location.search);

export const GameConfig = Object.freeze({
  world: {
    seed: 47381,
    unitsPerMeter: 1,
    chunkSizeMeters: 192,
    activeChunkRadius: 1,
    unloadChunkRadius: 2,
    maxChunkCreatesPerUpdate: 1,
    floatingOriginThresholdMeters: 640,
    defaultRegion: 'us-seattle-central',
    roomDensity: .72,
    propDensity: .68,
    scale: { unitsPerMeter: 1, doorwayHeight: 2.2, hallwayHeight: 2.6 },
  },
  player: {
    walkSpeed: 4.25,
    sprintSpeed: 7.2,
    acceleration: 28,
    deceleration: 34,
    gravity: 18,
    jumpVelocity: 6.4,
    terminalFallSpeed: 22,
    height: 1.78,
    radius: 0.32,
  },
  camera: {
    distance: 7.4,
    minDistance: 1.35,
    maxDistance: 12,
    targetHeight: 1.42,
    sensitivity: 0.006,
    minPitch: 0.12,
    maxPitch: 1.15,
    smoothness: 0.0025,
  },
  rendering: {
    renderDistance: 310,
    shadowQuality: 'adaptive',
    maxPixelRatio: 2,
    balancedPixelRatio: 1.35,
  },
  debug: {
    enabled: query.has('debug'),
    collisions: query.get('debug')?.includes('collisions') || query.has('debugCollisions'),
    player: query.get('debug')?.includes('player') || query.has('debugPlayer'),
    camera: query.get('debug')?.includes('camera') || query.has('debugCamera'),
    generation: query.get('debug')?.includes('generation') || query.has('debugGeneration'),
    raycasts: query.get('debug')?.includes('raycasts') || query.has('debugRaycasts'),
    chunks: query.get('debug')?.includes('chunks') || query.has('debugChunks'),
    coordinates: query.has('debugGeo'),
  },
});
