import * as THREE from 'three';
import './style.css';

const ageGate = document.querySelector('#age-gate');
document.querySelector('#enter-btn').onclick = () => { ageGate.classList.add('hidden'); startGame(); };
let started = false, rep = 12, cash = 240, selected = null, mode = 'exterior', floor = 1, currentRoom = null, worldSocket = null, lastNetworkSend = 0;

function setServerStatus(label, color) { const el = document.querySelector('#server-status'); if (el) { el.textContent = label; el.style.color = color; } }
function connectWorld() { const base = window.STH_WORLD_URL || `ws://${location.hostname || '127.0.0.1'}:8000`; const url = `${base.replace(/\/$/, '')}/ws/sth-city-01?player_id=browser-${Math.random().toString(36).slice(2, 10)}&display_name=Guest`; try { worldSocket = new WebSocket(url); worldSocket.addEventListener('open', () => { setServerStatus('ONLINE', '#58e39c'); toast('Connected to the world host.'); }); worldSocket.addEventListener('message', event => { const message = JSON.parse(event.data); if (message.type === 'welcome') setServerStatus('ONLINE', '#58e39c'); if (message.type === 'chat') toast(`${message.displayName}: ${message.text}`); }); worldSocket.addEventListener('close', () => setServerStatus('OFFLINE', '#ff775d')); worldSocket.addEventListener('error', () => setServerStatus('OFFLINE', '#ff775d')); } catch (_) { setServerStatus('LOCAL', '#39e4ff'); } }

function startGame(){
  if (started) return; started = true; connectWorld();
  const canvas = document.querySelector('#game');
  const scene = new THREE.Scene(); scene.background = new THREE.Color(0x090914); scene.fog = new THREE.Fog(0x090914, 18, 70);
  const camera = new THREE.PerspectiveCamera(58, innerWidth / innerHeight, .1, 120);
  camera.position.set(0, 7, 16);
  const renderer = new THREE.WebGLRenderer({ canvas, antialias: true }); renderer.setPixelRatio(Math.min(devicePixelRatio, 2)); renderer.setSize(innerWidth, innerHeight); renderer.shadowMap.enabled = true;
  scene.add(new THREE.HemisphereLight(0xffd3f4, 0x111126, 1.8));
  const pink = new THREE.PointLight(0xff3fbf, 38, 32); pink.position.set(0, 9, 3); pink.castShadow = true; scene.add(pink);
  const blue = new THREE.PointLight(0x28d9ff, 28, 28); blue.position.set(-12, 5, -8); scene.add(blue);
  const mat = (c, e = 0) => new THREE.MeshStandardMaterial({ color: c, roughness: .55, metalness: .25, emissive: e ? c : 0, emissiveIntensity: e });
  const box = (x, y, z, sx, sy, sz, c, parent = scene) => { const m = new THREE.Mesh(new THREE.BoxGeometry(sx, sy, sz), mat(c)); m.position.set(x, y, z); m.castShadow = true; m.receiveShadow = true; parent.add(m); return m; };
  const floorMat = mat(0x151527); const world = new THREE.Group(); scene.add(world); const interior = new THREE.Group(); interior.visible = false; scene.add(interior); const roomScene = new THREE.Group(); roomScene.visible = false; scene.add(roomScene);
  const guests = [];
  function makeGuest(i, parent = world) { const g = new THREE.Group(); const colors = [0xff5b9e, 0x56d7ff, 0xffc857, 0xa97cff, 0xff775d, 0x58e39c]; const body = new THREE.Mesh(new THREE.CapsuleGeometry(.42, 1.15, 5, 10), mat(colors[i % colors.length])); body.position.y = 1.05; g.add(body); const head = new THREE.Mesh(new THREE.SphereGeometry(.34, 16, 12), mat(0xf0b49d)); head.position.y = 1.95; g.add(head); const glow = new THREE.Mesh(new THREE.TorusGeometry(.58, .035, 8, 24), mat(0x22e4ff, 1)); glow.rotation.x = Math.PI / 2; glow.position.y = .06; g.add(glow); g.userData = { name: ['Nova', 'Jett', 'Mia', 'Roxy', 'Lux', 'Sage', 'Vee'][i % 7], mood: ['DANCING', 'CHILL', 'FLIRTING', 'VIBING'][i % 4], phase: i * .8 }; parent.add(g); return g; }
  function buildExterior() { box(0, -.2, 0, 36, .4, 34, 0x151527, world); const grid = new THREE.GridHelper(34, 34, 0x9b2e91, 0x3a1a48); grid.position.y = .02; world.add(grid); box(-16, 5, 0, 1, 10, 34, 0x22132f, world); box(16, 5, 0, 1, 10, 34, 0x22132f, world); box(0, 8, -16, 32, 16, 1, 0x1b142b, world); for (let y = 2; y < 9; y += 2.3) { box(0, y, -13, 29, .18, .35, 0x61305e, world); for (let x = -12; x <= 12; x += 3) box(x, y + .75, -13, .9, 1.2, .12, 0x29b8e8, world); } box(0, 3, -15.3, 9, 6, .5, 0x160d25, world); box(0, 7, -15.7, 11, 1.3, .25, 0xff28b5, world); box(-8, 1, -5, 7, .4, 4, 0x442043, world); box(-8, 2, -6.5, 5, 2, .25, 0x10c5d9, world); box(8, 1, -6, 6, .4, 3, 0x30204b, world); box(8, 2, -6.8, 5, 1.8, .3, 0xd72a86, world); for (let i = 0; i < 16; i++) { const g = makeGuest(i); g.position.set((i % 8 - 3.5) * 2.3, 0, Math.floor(i / 8) * 3 - 1); guests.push(g); } }
  function buildInterior() { box(0, -.2, 0, 22, .4, 34, 0x171321, interior); const g = new THREE.GridHelper(22, 22, 0x563a68, 0x281b38); g.position.y = .03; interior.add(g); box(-11, 3, 0, .5, 6, 34, 0x271531, interior); box(11, 3, 0, .5, 6, 34, 0x271531, interior); box(0, 5, -16, 22, 1, .5, 0x2a1836, interior); box(0, .1, 0, 2.2, .15, 34, 0xff32b5, interior); for (let r = 1; r <= 10; r++) { const z = 15 - r * 3; const left = box(-9.8, 1.7, z, .25, 2.3, 1.7, 0x38d7ee, interior); left.userData.room = (floor - 1) * 10 + r; const right = box(9.8, 1.7, z, .25, 2.3, 1.7, 0xff3fbf, interior); right.userData.room = (floor - 1) * 10 + r; box(-10.2, .2, z, .5, .2, 1.9, 0x3b2355, interior); box(10.2, .2, z, .5, .2, 1.9, 0x3b2355, interior); } for (let i = 0; i < 6; i++) { const g = makeGuest(i, interior); g.position.set((i % 2 ? 3 : -3), 0, i * 4 - 10); guests.push(g); } }
  function buildCity() { const city = new THREE.Group(); world.add(city); box(0, -.28, 0, 80, .3, 80, 0x0c1020, city); for (let i = -4; i <= 4; i++) { box(i * 10, -.05, 0, 2.2, .12, 80, 0x25283c, city); box(0, -.04, i * 10, 80, .11, 2.2, 0x25283c, city); box(i * 10, .02, 0, .06, .06, 80, 0xffcf67, city); box(0, .02, i * 10, 80, .06, .06, 0xffcf67, city); } const palette = [0x2d3150, 0x3b2450, 0x263e55, 0x49304f, 0x293b49]; for (let gx = -3; gx <= 3; gx++) for (let gz = -3; gz <= 3; gz++) { if (Math.abs(gx) <= 1 && Math.abs(gz) <= 1) continue; const x = gx * 10 + (Math.random() - .5) * 2, z = gz * 10 + (Math.random() - .5) * 2; if (Math.random() < .15) { box(x, .12, z, 6.8, .24, 6.8, 0x17372e, city); for (let t = 0; t < 4; t++) { const tree = new THREE.Group(); const trunk = new THREE.Mesh(new THREE.CylinderGeometry(.12, .16, 1.4, 8), mat(0x553524)); trunk.position.y = .8; tree.add(trunk); const crown = new THREE.Mesh(new THREE.SphereGeometry(.8, 10, 8), mat(0x1c9b78, 1)); crown.position.y = 1.8; tree.add(crown); tree.position.set(x + (t % 2 ? 1.8 : -1.8), 0, z + (t > 1 ? 1.8 : -1.8)); city.add(tree); } } else { const h = 3 + Math.random() * 9, w = 4.5 + Math.random() * 3, d = 4.5 + Math.random() * 3; box(x, h / 2, z, w, h, d, palette[Math.floor(Math.random() * palette.length)], city); for (let yy = 1.5; yy < h - .2; yy += 1.5) for (let xx = -w * .28; xx <= w * .28; xx += 1.2) { const window = box(x + xx, yy, z - d / 2 - .03, .48, .48, .05, Math.random() < .35 ? 0xff39b5 : 0x37d9ed, city); window.material.emissive = window.material.color; window.material.emissiveIntensity = .8; } } } for (let i = -3; i <= 3; i++) for (let j = -3; j <= 3; j++) { if ((i + j) % 2) continue; const lamp = new THREE.Group(); box(0, 2.1, 0, .08, 4.2, .08, 0x343649, lamp); const light = new THREE.Mesh(new THREE.SphereGeometry(.18, 10, 8), mat(0xffd06a, 1)); light.position.y = 4.2; lamp.add(light); lamp.position.set(i * 10 + 3.3, 0, j * 10 + 3.3); city.add(lamp); } }
  function buildRoom(n) { roomScene.clear(); roomScene.add(new THREE.AmbientLight(0xffc7e8, 1.4)); const r = n % 6; box(0, -.2, 0, 16, .4, 16, 0x1b1526, roomScene); box(0, 4, -8, 16, 8, .4, 0x251834, roomScene); box(-7, 3, 0, .4, 6, 16, 0x291a35, roomScene); box(7, 3, 0, .4, 6, 16, 0x291a35, roomScene); box(-2.6, .7, -2, 4.7, .55, 7, r % 2 ? 0x35265b : 0x4b214b, roomScene); box(-2.6, 1.2, -4.5, 4.7, .65, 1.5, 0xe6d6ec, roomScene); box(3.6, 1, 1.8, 2.1, 1.1, 1.1, 0x522143, roomScene); box(3.6, 1.75, 1.8, 2.3, .12, 1.2, 0x26d9ec, roomScene); box(3.6, .12, -5.5, 2.8, .2, 2, 0x3b234c, roomScene); box(4.8, .85, -5.5, .6, 1.6, 1.2, 0xff39b5, roomScene); box(-5.5, 2.5, -7.7, 4, 2.2, .15, 0x29d9ed, roomScene); box(0, 7, -7.7, 7, .15, .15, 0xff36b8, roomScene); for (let i = 0; i < 4; i++) box(-6 + i * 4, .2, 6.5, 1.7, .2, 1.7, 0x392242, roomScene); camera.position.set(0, 5.7, 12); roomScene.visible = true; interior.visible = false; world.visible = false; currentRoom = n; mode = 'room'; document.querySelector('#objective').textContent = `Room ${n} · suite view`; toast(`Entered suite ${n}.`); }
  buildExterior(); buildCity(); buildInterior();
  const roomList = document.querySelector('#room-list'); for (let n = 1; n <= 50; n++) { const b = document.createElement('button'); b.textContent = `ROOM ${String(n).padStart(2, '0')}`; b.onclick = () => { document.querySelector('#room-panel').classList.remove('open'); buildRoom(n); }; roomList.appendChild(b); }
  document.querySelector('#close-rooms').onclick = () => document.querySelector('#room-panel').classList.remove('open');
  const ray = new THREE.Raycaster(), mouse = new THREE.Vector2(); canvas.addEventListener('pointerdown', e => { mouse.x = e.clientX / innerWidth * 2 - 1; mouse.y = -(e.clientY / innerHeight) * 2 + 1; ray.setFromCamera(mouse, camera); const hit = ray.intersectObjects(guests, true)[0]; if (hit) { selected = hit.object.parent; document.querySelector('#objective').textContent = `Talk to ${selected.userData.name} · ${selected.userData.mood}`; toast(`You caught ${selected.userData.name}'s attention.`); } });
  const keys = {}; addEventListener('keydown', e => { keys[e.key.toLowerCase()] = true; if (e.key.toLowerCase() === 'c') { mode = 'city'; world.visible = true; interior.visible = false; roomScene.visible = false; camera.position.set(27, 18, 27); document.querySelector('#objective').textContent = 'City district · explore the nightlife grid'; toast('City district loaded.'); } if (e.key.toLowerCase() === 'h') { mode = mode === 'exterior' ? 'interior' : 'exterior'; world.visible = mode === 'exterior'; interior.visible = mode === 'interior'; roomScene.visible = false; camera.position.set(0, 6, mode === 'exterior' ? 16 : 13); document.querySelector('#objective').textContent = mode === 'interior' ? `Hotel interior · Floor ${floor}` : 'Make a memorable entrance'; toast(mode === 'interior' ? 'Welcome inside the hotel.' : 'Back outside at the plaza.'); } if (/^[1-5]$/.test(e.key)) { floor = Number(e.key); mode = 'interior'; world.visible = false; interior.visible = true; roomScene.visible = false; document.querySelector('#objective').textContent = `Hotel interior · Floor ${floor}`; toast(`Floor ${floor} selected · rooms ${(floor - 1) * 10 + 1}-${floor * 10}`); } if (e.key.toLowerCase() === 'r') document.querySelector('#room-panel').classList.add('open'); if (e.key === 'Escape') { roomScene.visible = false; mode = 'interior'; interior.visible = true; document.querySelector('#objective').textContent = `Hotel interior · Floor ${floor}`; } }); addEventListener('keyup', e => keys[e.key.toLowerCase()] = false);
  document.querySelector('#interact').onclick = () => { if (selected) { rep += 3; cash += 25; update(); toast(`Good energy with ${selected.userData.name}! +3 REP · +$25`); selected = null; document.querySelector('#objective').textContent = 'Find your next connection'; } else if (mode === 'exterior') { mode = 'interior'; world.visible = false; interior.visible = true; camera.position.set(0, 6, 13); toast('You walked through the hotel entrance.'); } };
  function update() { document.querySelector('#rep').textContent = rep; document.querySelector('#cash').textContent = cash; } function toast(t) { const el = document.querySelector('#toast'); el.textContent = t; el.classList.add('show'); clearTimeout(window.tt); window.tt = setTimeout(() => el.classList.remove('show'), 2300); }
  addEventListener('resize', () => { camera.aspect = innerWidth / innerHeight; camera.updateProjectionMatrix(); renderer.setSize(innerWidth, innerHeight); });
  const clock = new THREE.Clock(); function loop() { requestAnimationFrame(loop); const t = clock.getElapsedTime(); for (const g of guests) { g.position.y = Math.sin(t * 2 + (g.userData.phase || 0)) * .06; g.rotation.y = Math.sin(t * .5 + (g.userData.phase || 0)) * .35; if (g.children[2]) g.children[2].rotation.z = t * 2; } let dx = 0, dz = 0; if (keys.w) dz -= 1; if (keys.s) dz += 1; if (keys.a) dx -= 1; if (keys.d) dx += 1; if (worldSocket && worldSocket.readyState === WebSocket.OPEN && t - lastNetworkSend > .05) { worldSocket.send(JSON.stringify({ type: 'input', x: dx, z: dz })); lastNetworkSend = t; } camera.position.x += dx * .12; camera.position.z += dz * .12; camera.position.x = THREE.MathUtils.clamp(camera.position.x, -14, 14); camera.position.z = THREE.MathUtils.clamp(camera.position.z, -14, 17); camera.lookAt(camera.position.x * .15, mode === 'room' ? 2 : 2, mode === 'room' ? -2 : 0); renderer.render(scene, camera); } loop();
}
