const { app, BrowserWindow, ipcMain, protocol, net, session } = require('electron');
const fs = require('node:fs');
const path = require('node:path');
const { pathToFileURL } = require('node:url');
const { UpdateService } = require('./updater/UpdateService');
const { readBuildInfo } = require('./updater/VersionService');
const { installSecurity } = require('./security');
const { setupPermissions } = require('./permissions');
protocol.registerSchemesAsPrivileged([{ scheme: 'sth', privileges: { standard: true, secure: true, supportFetchAPI: true, corsEnabled: true, stream: true } }]);
const isDev = !app.isPackaged; let launcher; let game; let update; let logFile;
function log(message) { try { fs.appendFileSync(logFile, `${new Date().toISOString()} ${message}\n`); } catch {} }
function runtimeRoot() { return isDev ? path.join(__dirname, '..', 'game-runtime') : path.join(app.getAppPath(), 'game-runtime'); }
function buildInfo() { try { return readBuildInfo(runtimeRoot()); } catch { return { version: app.getVersion(), shortCommit: 'unknown', buildNumber: 'unknown' }; } }
function trusted(sender) { return sender === launcher?.webContents || sender === game?.webContents; }
function createLauncher() { launcher = new BrowserWindow({ width: 1180, height: 760, minWidth: 900, minHeight: 600, backgroundColor: '#080b10', webPreferences: { preload: path.join(__dirname, 'preload.js'), contextIsolation: true, nodeIntegration: false, sandbox: true } }); launcher.loadFile(path.join(__dirname, '..', 'launcher', 'index.html')); launcher.on('closed', () => { launcher = null; if (game && !game.isDestroyed()) game.close(); }); }
function createGame() { if (game && !game.isDestroyed()) return game.focus(); game = new BrowserWindow({ width: 1440, height: 900, minWidth: 960, minHeight: 600, title: 'Subway Thots Hotel', backgroundColor: '#05070a', webPreferences: { preload: path.join(__dirname, 'preload.js'), contextIsolation: true, nodeIntegration: false, sandbox: true } }); game.webContents.on('did-fail-load', (_event, code, description, validatedURL) => { log(`[game] failed load code=${code} description=${description} url=${validatedURL}`); if (launcher && !launcher.isDestroyed()) launcher.webContents.send('game-error', description); }); game.webContents.on('did-finish-load', () => log(`[game] loaded ${game.webContents.getURL()} runtime=${runtimeRoot()}`)); game.loadURL(isDev ? (process.env.STH_DEV_SERVER || 'http://127.0.0.1:5180/') : 'sth://game/index.html'); game.webContents.on('render-process-gone', (_e, details) => { log(`[game] render process gone ${details.reason}`); if (launcher && !launcher.isDestroyed()) launcher.webContents.send('game-error', details.reason); }); game.on('closed', () => { game = null; if (launcher && !launcher.isDestroyed()) { launcher.show(); launcher.webContents.send('returned-to-launcher'); } }); }
ipcMain.handle('desktop:get-state', (event) => { if (!trusted(event.sender)) throw new Error('Unauthorized sender'); return { appVersion: app.getVersion(), build: buildInfo(), update: update.state }; });
ipcMain.handle('desktop:check-updates', async (event) => { if (!trusted(event.sender)) throw new Error('Unauthorized sender'); return update.check(); });
ipcMain.handle('desktop:download-update', async (event) => { if (!trusted(event.sender)) throw new Error('Unauthorized sender'); return update.download(); });
ipcMain.handle('desktop:install-update', (event) => { if (!trusted(event.sender)) throw new Error('Unauthorized sender'); update.install(); return update.state; });
ipcMain.handle('desktop:launch-game', (event) => { if (!trusted(event.sender)) throw new Error('Unauthorized sender'); createGame(); launcher?.hide(); return { ok: true }; });
ipcMain.handle('desktop:return-launcher', (event) => { if (!trusted(event.sender)) throw new Error('Unauthorized sender'); game?.close(); launcher?.show(); return { ok: true }; });
ipcMain.handle('desktop:get-settings', () => { const file = path.join(app.getPath('userData'), 'settings.json'); try { return JSON.parse(fs.readFileSync(file, 'utf8')); } catch { return { fullscreen: false, graphics: 'high' }; } });
ipcMain.handle('desktop:save-settings', (event, settings) => { if (!trusted(event.sender) || !settings || typeof settings !== 'object') throw new Error('Unauthorized settings write'); fs.writeFileSync(path.join(app.getPath('userData'), 'settings.json'), JSON.stringify({ fullscreen: Boolean(settings.fullscreen), graphics: String(settings.graphics || 'high').slice(0, 20) }, null, 2)); return { ok: true }; });
app.whenReady().then(() => { logFile = path.join(app.getPath('userData'), 'desktop-client.log'); log('[app] startup'); setupPermissions(); installSecurity('sth', log); protocol.handle('sth', async (request) => { const relative = decodeURIComponent(new URL(request.url).pathname).replace(/^\/+/, ''); const root = path.resolve(runtimeRoot()); const target = path.resolve(root, relative); if (target !== root && !target.startsWith(`${root}${path.sep}`)) return new Response('Forbidden', { status: 403 }); return net.fetch(pathToFileURL(target).toString()); }); update = new UpdateService((state) => { launcher?.webContents.send('update-state', state); }, log); update.configure(); createLauncher(); if (process.argv.includes('--play')) setTimeout(() => { createGame(); launcher?.hide(); }, 500); setTimeout(() => update.check(), 1800); });
app.on('window-all-closed', () => { if (process.platform !== 'darwin') app.quit(); });
